import Head from 'next/head';
import { Description } from '../components/main/description';
import { Faq } from '../components/main/faq';
import { Footer } from '../components/main/footer';
import { Header } from '../components/main/header';
import { Hero } from '../components/main/hero';
import { Registration } from '../components/main/registration';
import { Schedule } from '../components/main/schedule';
import { Sponsors } from '../components/main/sponsors';
import { Team } from '../components/main/team';
import { Timeline } from '../components/main/timeline';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <Hero />
        <Description />
        <Timeline />
        <Schedule />
        <Sponsors />
        <Team />
        <Faq />
        <Registration />
        <Footer />
      </main>
    </>
  );
}
